
#inputs
character = input('Enter a boy name: ')
place = input('Enter any place: (e.g. beach, library )')
object = input('Enter any object: ')

#story
print('\n The Story Generated by your input values')

print(f'Once upon a time, {character} was walking through {place} when he stumbled upon the {object}. Little did they know, this discovery would change their life forever')